package com.david122.answer.model;

public class Role {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.role_id
     * @mbg.generated  Thu Jan 11 13:37:36 CST 2018
     */
    private String roleId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.role_code
     * @mbg.generated  Thu Jan 11 13:37:36 CST 2018
     */
    private String roleCode;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.role_name
     * @mbg.generated  Thu Jan 11 13:37:36 CST 2018
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.role_id
     * @return  the value of role.role_id
     * @mbg.generated  Thu Jan 11 13:37:36 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.role_id
     * @param roleId  the value for role.role_id
     * @mbg.generated  Thu Jan 11 13:37:36 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.role_code
     * @return  the value of role.role_code
     * @mbg.generated  Thu Jan 11 13:37:36 CST 2018
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.role_code
     * @param roleCode  the value for role.role_code
     * @mbg.generated  Thu Jan 11 13:37:36 CST 2018
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.role_name
     * @return  the value of role.role_name
     * @mbg.generated  Thu Jan 11 13:37:36 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.role_name
     * @param roleName  the value for role.role_name
     * @mbg.generated  Thu Jan 11 13:37:36 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
}